### ISSUE TITLE
Road map to becoming the best note taking app

### ISSUE THREAD

**Issue by z3t0** [z3t0/pkm#9]
Brainstorming below:

- [ ] runs on all major platforms
- [ ] supports handwriting
- [ ] supports password protected notes
- [ ] easy to use saas hosted app
- [ ] instant search of the entire notes index; tbd instant and entire 
- [ ] markdown notes
- [ ] syntax highlighting blocks
- [ ] canvas based unified object editor - rich wsiwyg type for text, handweiring, tasks etc. 
- [ ] vim bindings
- [ ] 

I'm not sure about plugin support. I worry it may result in less reliable experienced and half baked features. But the whole thing is open source so it can be extended directly.
